spring:
  application:
    name: Exchange rate service
  datasource:
    url: jdbc:postgresql://exchange-rate-db:5432/exchangerate_db
    username: exchangerate_db_user
    password: exchangerate_db_pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    co.spribe.exchangerate: DEBUG

fixer:
  api:
    base-url: https://data.fixer.io/api
    access-key: 7cbf61aef39331e9c55bbf22b7ab0842

scheduler:
  update-exchange-rates-cron: "0 0 * * * ?"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

registry:
  reentrantLock:
    enabled: false
  concurrentHashMap:
    enabled: true

